"""Ports — abstract interfaces the application core depends on. Implemented by outbound adapters."""
from datetime import datetime
from typing import Any, Dict, List, Optional, Protocol

from app.domain.models import (
    BaseProfile,
    CvData,
    Generation,
    GenerationSummary,
    LetterData,
    OAuthProfile,
    Session,
    User,
)


class UserRepository(Protocol):
    async def find_by_email(self, email: str) -> Optional[User]: ...
    async def find_by_id(self, user_id: str) -> Optional[User]: ...
    async def count_admins(self) -> int: ...
    async def insert(self, user: User) -> None: ...
    async def update_profile(self, user_id: str, name: str, picture: Optional[str]) -> None: ...


class SessionRepository(Protocol):
    async def insert(self, session: Session) -> None: ...
    async def find_by_token(self, token: str) -> Optional[Session]: ...
    async def delete_by_token(self, token: str) -> None: ...


class GenerationRepository(Protocol):
    async def insert(self, generation: Generation) -> None: ...
    async def list_summaries(self, owner_id: Optional[str], limit: int) -> List[GenerationSummary]: ...
    async def find_by_id(self, gen_id: str, owner_id: Optional[str]) -> Optional[Generation]: ...
    async def update(self, gen_id: str, owner_id: Optional[str], patch: Dict[str, Any]) -> Optional[Generation]: ...
    async def delete(self, gen_id: str, owner_id: Optional[str]) -> bool: ...
    async def claim_orphans(self, user_id: str) -> None: ...


class BaseProfileRepository(Protocol):
    async def find(self, user_id: str) -> Optional[BaseProfile]: ...
    async def upsert(self, profile: BaseProfile) -> None: ...
    async def delete(self, user_id: str) -> None: ...
    async def claim_orphans(self, user_id: str) -> None: ...


class LlmPort(Protocol):
    async def complete(self, system_prompt: str, user_text: str) -> str: ...


class DocumentTextExtractor(Protocol):
    def extract(self, filename: str, content: bytes) -> str: ...


class WebPageFetcher(Protocol):
    def fetch_text(self, url: str) -> str: ...


class OAuthProvider(Protocol):
    def fetch_profile(self, session_id: str) -> OAuthProfile: ...


class DocumentRenderer(Protocol):
    def cv_pdf(self, cv: CvData, layout: str) -> bytes: ...
    def cv_docx(self, cv: CvData) -> bytes: ...
    def letter_pdf(self, letter: LetterData, sender_cv: CvData, company: str) -> bytes: ...
    def letter_docx(self, letter: LetterData, sender_cv: CvData, company: str) -> bytes: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class IdGenerator(Protocol):
    def new_id(self) -> str: ...
